- thinky_front/src/components/UserEdit.js
ユーザー情報編集ページの作成
ユーザーが情報を編集したいときに必要なため
> Add:view_user_edit

- thinky_front/package-lock.json
- thinky_front/package.json
- thinky_front/src/App.js
- thinky_front/src/components/WhyModal.js
- thinky_front/src/styles/WhyModal.module.scss
共通で使用するモーダル部分のビューを作成。
コンポーネントを繰り返し使うことで、不必要なコーディングを避けるため。
> Add: created whyModal component

- thinky_front/src/components/Footer.js
- thinky_front/src/components/Header.js
- thinky_front/src/components/Layout.js
layoutコンポーネントを作成。
複数ページで共通して表示されるヘッダーやフッターのコンポーネントをまとめておくため。
> Add: created layout component

- thinky_front/package-lock.json
- thinky_front/package.json
- thinky_front/src/components/UserMypage.js
ユーザーマイページのビューのHTMLを書いた。
ユーザーのマイページが必要なため
> Add view user mypage

- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/index.js
- thinky_front/src/styles/EveryoneWhy.module.scss
みんなのWHYのページの作成
userがみんなのWHYの一覧を見れるようにするためのviewを作成する必要があったため
> add:view_everyone's_why

- thinky_front/src/App.js
- thinky_front/src/components/UserMypage.js
- thinky_front/src/styles/UserMypage.module.scss
ユーザーのマイページを作成
マイページを作成し、ユーザーにとって扱いやすいAPPを作るため
> add:view_user_mypage

- thinky_front/src/App.js
- thinky_front/src/components/SignIn.js
- thinky_front/src/components/SignUp.js
ログイン新規登録画面の実装
ユーザー登録したユーザーにのみアプリを使用できるようにしてセキュリティを向上させるため。
> ログイン新規登録画面実装

- thinky_front/src/App.js
- thinky_front/src/components/ChatPage.js
- thinky_front/src/components/Footer.js
- thinky_front/src/components/Layout.js
- thinky_front/src/styles/ChatPage.module.scss
- thinky_front/src/styles/WhyModal.module.scss
ユーザーが「Why」を深掘りするためのチャット形式のビューを作成。
ひたすらページ内のフォームの中で自問自答するよりも、アプリ側から「Why?」と尋ねられる方がAnswerを答えやすいから。
> Add: Feature/chat page

- thinky_front/README.md
- thinky_front/src/components/App.js
- thinky_front/src/components/ChatPage.js
- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/Footer.js
- thinky_front/src/components/Header.js
- thinky_front/src/components/Home.js
- thinky_front/src/components/Layout.js
- thinky_front/src/components/Question.js
- thinky_front/src/components/SignIn.js
- thinky_front/src/components/SignUp.js
- thinky_front/src/components/UserEdit.js
- thinky_front/src/components/UserMypage.js
- thinky_front/src/components/WhiesList.js
- thinky_front/src/components/WhyModal.js
- thinky_front/src/index.js
Keeping track of what has been installed as dependency is important for your project.
It is a general recommendation. __response(or res), error(or err)__
1. Variable name which has boolean is recommended to be like this 
> isVariableName
It follows 2 rules. (camelCase, booleanCase)
2. React Hook supports inline function 
inline function is more simple unless it is not complicating or re-used
import everthing without commenting is not sexy
Simple bug fix
Hey, I have noticed that Below Copyright function is found in several components.
```javascript
function Copyright() {
return (
<Typography variant="body2" color="textSecondary" align="center">
{"Copyright © "}
<Link color="inherit" href="https://material-ui.com/">
Thinky
</Link>{" "}
{new Date().getFullYear()}
{"."}
</Typography>
)
}
``` …
> 🔥 Commit from Terada

- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/WhiesList.js
everyoneWhy.jsにて、classコンポーネントをfunctionコンポーネントに変更
makestyleなどを使えるように変更した。
> change:component:class->function

- app/controllers/answers_controller.rb
- config/routes.rb
- test/controllers/answers_controller_test.rb
- thinky_front/src/components/Answer.js
- thinky_front/src/components/ChatPage.js
- thinky_front/src/components/WhyModal.js
- thinky_front/src/styles/ChatPage.module.scss
「Why」の深掘りをするチャット形式ページで、送信したメッセージと「Why?」がフォームの上部に表示されるようにした。なお、送信されたデータはDBに保存される。
フォームにひたすら考えた理由を入力し続けるのに比べて、メッセージで「Why？」と尋ねられた方が答えなければと感じやすいから。
> From dev/tomoya

- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/WhiesList.js
みんなのwhy共有ページにて、questionのよる検索機能の実装
検索をして自分の調べたいwhyを見つけやすくするため
> add:searchFunction

- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/WhiesList.js
ジャンル検索機能の作成
ジャンルで検索できることにより、よりユーザーが使いやすい検索機能にするため。
> add:category-search-function

- thinky_front/src/components/App.js
- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/Question.js
- thinky_front/src/components/UserMypage.js
- thinky_front/src/components/WhiesList.js
mypageから設定ボタンへのリンクを歯車アイコンに付与
マイページから設定へ飛べるようにするため
> add:link_to_editMypage

- thinky_front/src/components/EveryoneWhy.js
> Test: EveryoneWhy

- thinky_front/src/components/EveryoneWhy.js
genreidのusestateや、genreのvalueを変更した
エラー解決のため
> fix:usestate

- thinky_front/src/components/Question.js
みんなのwhyページから個別のwhyページに飛ぶことができるように設定した。
個別のwhyページを見ることができるようになるため
> add:connection_from_everyonWhy_to_chatpage

- app/controllers/whies_controller.rb
- app/models/pb_answer.rb
- app/models/why.rb
- config/routes.rb
- thinky_front/src/components/Question.js
みんなのwhyページにおいて、whyに対する答えの数を見ることができるようになった。
みんなのwhyページで、回答の数を見ることができる方がユーザにとって使いやすいため
> add:sharepage_count_of_answer

- app/controllers/whies_controller.rb
- config/routes.rb
- thinky_front/src/components/App.js
- thinky_front/src/components/UserMypage.js
- thinky_front/src/components/WhyTab.js
ユーザーのマイぺージにて、自分のwhyを表示できるようにした。
ユーザーにとって自分のマイページを見れた方が良いため。
> add:mypage_mywhy

- app/controllers/registrations_controller.rb
- config/routes.rb
- thinky_front/src/components/App.js
- thinky_front/src/components/UserEdit.js
- thinky_front/src/components/UserMypage.js
ユーザーのマイページにて、パスワードなどのユーザーの情報を編集可能にした。
ユーザーの情報を変更できれば、より使いやすくなるため。
> add:func_user_edit

- app/controllers/whies_controller.rb
- config/routes.rb
- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/WhiesList.js
複数検索（and）を実装した。
whyを検索する際に、複数のwordで検索できる方が便利だから。
> add:func_and_search

- thinky_front/src/components/ChatHeader.js
- thinky_front/src/components/ChatPage.js
- thinky_front/src/components/LikeForChatHeader.js
- thinky_front/src/styles/ChatPage.module.scss
いいねボタンの位置をChatPageからChatHeaderに移した。
header部分にいいねボタンがある方が押しやすいから。
> いいね機能の場所移動

- app/controllers/whies_controller.rb
- config/routes.rb
- thinky_front/src/components/UserMypage.js
- thinky_front/src/components/WhyTab.js
ユーザーマイページにて、自分のwhyと、自分がいいねしたwhyを表示できるようにした。また、リンクを踏むと、当該whyのチャットページに飛ぶようにした。
ユーザーマイページから各々のチャットページに飛べる方が便利だから。
> add:add_link_for_why_INusermypage

- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/sessions_controller.rb
- thinky_front/src/components/Like.js
- thinky_front/src/components/SignIn.js
- thinky_front/src/components/SignUp.js
- thinky_front/src/components/UserValidation.js
ユーザー登録ログイン画面でのフォームのバリデーション機能の追加(メールアドレス、パスワード文字数など)
不正なアドレスやパスワードが入力された時にエラーメッセージを表示して、ユーザーに知らせるため。
> ユーザー入力フォームのバリデーション

- thinky_front/src/components/App.js
- thinky_front/src/components/ChatHeader.js
- thinky_front/src/components/ChatPage.js
- thinky_front/src/components/Footer.js
- thinky_front/src/components/Header.js
- thinky_front/src/components/Home.js
- thinky_front/src/components/Layout.js
- thinky_front/src/components/Like.js
- thinky_front/src/components/SignIn.js
- thinky_front/src/components/SignUp.js
- thinky_front/src/components/UserEdit.js
- thinky_front/src/styles/Layout.module.scss
ホームページとログイン・ログアウト・編集ページのデザインを修正した。
+ ChatPageのログアウト機能も動くようにした。
ユーザビリティ向上のため。
> デザインの修正 +α

- thinky_front/package-lock.json
- thinky_front/package.json
- thinky_front/src/components/App.js
- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/components/UserMypage.js
- thinky_front/src/styles/EveryoneWhy.module.scss
- thinky_front/src/styles/UserMypage.module.scss
fontawsome の導入、cssの微修正
より使いやすいデザインにするため
> fix:css_icon_fontawsome

- thinky_front/src/components/EveryoneWhy.js
- thinky_front/src/styles/EveryoneWhy.module.scss
- thinky_front/src/styles/UserMypage.module.scss
レスポンシブル対応をできるようにcssを変更
スマホでも見れるようにするため
> fix:css_add_mediaquery
